# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/MyProjects/toMateTo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/MyProjects/toMateTo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/MyProjects/toMateTo/CMakeFiles /home/MyProjects/toMateTo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/MyProjects/toMateTo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named toMateTo

# Build rule for target.
toMateTo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 toMateTo
.PHONY : toMateTo

# fast build rule for target.
toMateTo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/build
.PHONY : toMateTo/fast

chess_gui/gui.o: chess_gui/gui.cpp.o
.PHONY : chess_gui/gui.o

# target to build an object file
chess_gui/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/chess_gui/gui.cpp.o
.PHONY : chess_gui/gui.cpp.o

chess_gui/gui.i: chess_gui/gui.cpp.i
.PHONY : chess_gui/gui.i

# target to preprocess a source file
chess_gui/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/chess_gui/gui.cpp.i
.PHONY : chess_gui/gui.cpp.i

chess_gui/gui.s: chess_gui/gui.cpp.s
.PHONY : chess_gui/gui.s

# target to generate assembly for a file
chess_gui/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/chess_gui/gui.cpp.s
.PHONY : chess_gui/gui.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/main.cpp.s
.PHONY : main.cpp.s

toMateTo_engine/move_generation/chess_board.o: toMateTo_engine/move_generation/chess_board.cpp.o
.PHONY : toMateTo_engine/move_generation/chess_board.o

# target to build an object file
toMateTo_engine/move_generation/chess_board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/move_generation/chess_board.cpp.o
.PHONY : toMateTo_engine/move_generation/chess_board.cpp.o

toMateTo_engine/move_generation/chess_board.i: toMateTo_engine/move_generation/chess_board.cpp.i
.PHONY : toMateTo_engine/move_generation/chess_board.i

# target to preprocess a source file
toMateTo_engine/move_generation/chess_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/move_generation/chess_board.cpp.i
.PHONY : toMateTo_engine/move_generation/chess_board.cpp.i

toMateTo_engine/move_generation/chess_board.s: toMateTo_engine/move_generation/chess_board.cpp.s
.PHONY : toMateTo_engine/move_generation/chess_board.s

# target to generate assembly for a file
toMateTo_engine/move_generation/chess_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/move_generation/chess_board.cpp.s
.PHONY : toMateTo_engine/move_generation/chess_board.cpp.s

toMateTo_engine/move_generation/move_stack.o: toMateTo_engine/move_generation/move_stack.cpp.o
.PHONY : toMateTo_engine/move_generation/move_stack.o

# target to build an object file
toMateTo_engine/move_generation/move_stack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/move_generation/move_stack.cpp.o
.PHONY : toMateTo_engine/move_generation/move_stack.cpp.o

toMateTo_engine/move_generation/move_stack.i: toMateTo_engine/move_generation/move_stack.cpp.i
.PHONY : toMateTo_engine/move_generation/move_stack.i

# target to preprocess a source file
toMateTo_engine/move_generation/move_stack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/move_generation/move_stack.cpp.i
.PHONY : toMateTo_engine/move_generation/move_stack.cpp.i

toMateTo_engine/move_generation/move_stack.s: toMateTo_engine/move_generation/move_stack.cpp.s
.PHONY : toMateTo_engine/move_generation/move_stack.s

# target to generate assembly for a file
toMateTo_engine/move_generation/move_stack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/move_generation/move_stack.cpp.s
.PHONY : toMateTo_engine/move_generation/move_stack.cpp.s

toMateTo_engine/table_generation/knight_tables.o: toMateTo_engine/table_generation/knight_tables.cpp.o
.PHONY : toMateTo_engine/table_generation/knight_tables.o

# target to build an object file
toMateTo_engine/table_generation/knight_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/knight_tables.cpp.o
.PHONY : toMateTo_engine/table_generation/knight_tables.cpp.o

toMateTo_engine/table_generation/knight_tables.i: toMateTo_engine/table_generation/knight_tables.cpp.i
.PHONY : toMateTo_engine/table_generation/knight_tables.i

# target to preprocess a source file
toMateTo_engine/table_generation/knight_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/knight_tables.cpp.i
.PHONY : toMateTo_engine/table_generation/knight_tables.cpp.i

toMateTo_engine/table_generation/knight_tables.s: toMateTo_engine/table_generation/knight_tables.cpp.s
.PHONY : toMateTo_engine/table_generation/knight_tables.s

# target to generate assembly for a file
toMateTo_engine/table_generation/knight_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/knight_tables.cpp.s
.PHONY : toMateTo_engine/table_generation/knight_tables.cpp.s

toMateTo_engine/table_generation/magic_gen.o: toMateTo_engine/table_generation/magic_gen.cpp.o
.PHONY : toMateTo_engine/table_generation/magic_gen.o

# target to build an object file
toMateTo_engine/table_generation/magic_gen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_gen.cpp.o
.PHONY : toMateTo_engine/table_generation/magic_gen.cpp.o

toMateTo_engine/table_generation/magic_gen.i: toMateTo_engine/table_generation/magic_gen.cpp.i
.PHONY : toMateTo_engine/table_generation/magic_gen.i

# target to preprocess a source file
toMateTo_engine/table_generation/magic_gen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_gen.cpp.i
.PHONY : toMateTo_engine/table_generation/magic_gen.cpp.i

toMateTo_engine/table_generation/magic_gen.s: toMateTo_engine/table_generation/magic_gen.cpp.s
.PHONY : toMateTo_engine/table_generation/magic_gen.s

# target to generate assembly for a file
toMateTo_engine/table_generation/magic_gen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_gen.cpp.s
.PHONY : toMateTo_engine/table_generation/magic_gen.cpp.s

toMateTo_engine/table_generation/magic_helper_functions.o: toMateTo_engine/table_generation/magic_helper_functions.cpp.o
.PHONY : toMateTo_engine/table_generation/magic_helper_functions.o

# target to build an object file
toMateTo_engine/table_generation/magic_helper_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_helper_functions.cpp.o
.PHONY : toMateTo_engine/table_generation/magic_helper_functions.cpp.o

toMateTo_engine/table_generation/magic_helper_functions.i: toMateTo_engine/table_generation/magic_helper_functions.cpp.i
.PHONY : toMateTo_engine/table_generation/magic_helper_functions.i

# target to preprocess a source file
toMateTo_engine/table_generation/magic_helper_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_helper_functions.cpp.i
.PHONY : toMateTo_engine/table_generation/magic_helper_functions.cpp.i

toMateTo_engine/table_generation/magic_helper_functions.s: toMateTo_engine/table_generation/magic_helper_functions.cpp.s
.PHONY : toMateTo_engine/table_generation/magic_helper_functions.s

# target to generate assembly for a file
toMateTo_engine/table_generation/magic_helper_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_helper_functions.cpp.s
.PHONY : toMateTo_engine/table_generation/magic_helper_functions.cpp.s

toMateTo_engine/table_generation/magic_king_tables.o: toMateTo_engine/table_generation/magic_king_tables.cpp.o
.PHONY : toMateTo_engine/table_generation/magic_king_tables.o

# target to build an object file
toMateTo_engine/table_generation/magic_king_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_king_tables.cpp.o
.PHONY : toMateTo_engine/table_generation/magic_king_tables.cpp.o

toMateTo_engine/table_generation/magic_king_tables.i: toMateTo_engine/table_generation/magic_king_tables.cpp.i
.PHONY : toMateTo_engine/table_generation/magic_king_tables.i

# target to preprocess a source file
toMateTo_engine/table_generation/magic_king_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_king_tables.cpp.i
.PHONY : toMateTo_engine/table_generation/magic_king_tables.cpp.i

toMateTo_engine/table_generation/magic_king_tables.s: toMateTo_engine/table_generation/magic_king_tables.cpp.s
.PHONY : toMateTo_engine/table_generation/magic_king_tables.s

# target to generate assembly for a file
toMateTo_engine/table_generation/magic_king_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toMateTo.dir/build.make CMakeFiles/toMateTo.dir/toMateTo_engine/table_generation/magic_king_tables.cpp.s
.PHONY : toMateTo_engine/table_generation/magic_king_tables.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... toMateTo"
	@echo "... chess_gui/gui.o"
	@echo "... chess_gui/gui.i"
	@echo "... chess_gui/gui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... toMateTo_engine/move_generation/chess_board.o"
	@echo "... toMateTo_engine/move_generation/chess_board.i"
	@echo "... toMateTo_engine/move_generation/chess_board.s"
	@echo "... toMateTo_engine/move_generation/move_stack.o"
	@echo "... toMateTo_engine/move_generation/move_stack.i"
	@echo "... toMateTo_engine/move_generation/move_stack.s"
	@echo "... toMateTo_engine/table_generation/knight_tables.o"
	@echo "... toMateTo_engine/table_generation/knight_tables.i"
	@echo "... toMateTo_engine/table_generation/knight_tables.s"
	@echo "... toMateTo_engine/table_generation/magic_gen.o"
	@echo "... toMateTo_engine/table_generation/magic_gen.i"
	@echo "... toMateTo_engine/table_generation/magic_gen.s"
	@echo "... toMateTo_engine/table_generation/magic_helper_functions.o"
	@echo "... toMateTo_engine/table_generation/magic_helper_functions.i"
	@echo "... toMateTo_engine/table_generation/magic_helper_functions.s"
	@echo "... toMateTo_engine/table_generation/magic_king_tables.o"
	@echo "... toMateTo_engine/table_generation/magic_king_tables.i"
	@echo "... toMateTo_engine/table_generation/magic_king_tables.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

